#on: workflow_call
on: workflow_dispatch
name: Linkcheck
jobs:
  linkcheck:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - uses: filiph/linkcheck@2.0.23
      with:
        arguments: https://www.gnuu.de --connection-failures-as-warnings
